name: LSP

on:
  push:
    branches: [master]
    paths:
      - lsp/**
  pull_request:
    paths:
      - lsp/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: lsp/package-lock.json
          node-version: ${{ vars.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
        working-directory: lsp
      - name: Build
        run: npm run build
        working-directory: lsp
      - name: Lint
        run: npm run lint
        working-directory: lsp
